import { notFound } from 'next/navigation';
import { getPrisma } from '@/lib/db';

export default async function Page({
  params,
}: {
  params: Promise<{ date: string; slug: string }>;
}) {
  const { slug } = await params;
  const prisma = getPrisma();

  const article = await prisma.overviewArticle.findUnique({
    where: { slug },
  });

  if (!article) {
    // Next.js convention: notFound() renders the nearest not-found.tsx
    // (src/app/not-found.tsx already exists in this project) and returns a
    // real 404 status — silently rendering nothing here would instead give
    // visitors and crawlers an empty 200 page, which is worse for both UX
    // and SEO than a proper 404.
    notFound();
  }

  const displayDate = new Date(article.publishedDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <article className="overflow-hidden rounded-xl border border-neutral-200 bg-white shadow-sm">
        <div className="border-b border-neutral-200 px-6 py-5 sm:px-8">
          <div className="flex items-center gap-3 text-xs font-medium uppercase tracking-wide text-neutral-500">
            <span className="rounded-full bg-neutral-100 px-2.5 py-1 text-neutral-700">
              {article.category}
            </span>
            <time dateTime={new Date(article.publishedDate).toISOString()}>
              {displayDate}
            </time>
          </div>

          <h1 className="mt-3 text-2xl font-bold leading-tight text-neutral-900 sm:text-3xl">
            {article.title}
          </h1>

          <p className="mt-3 text-base leading-relaxed text-neutral-600">
            {article.summary}
          </p>
        </div>

        {/* article.body is a trusted HTML fragment generated by our own
           RunPod pipeline (see overview-service.ts), not user-submitted
           content, so rendering it directly here is safe.

           Styling is hand-written via Tailwind's arbitrary child-selector
           syntax rather than the @tailwindcss/typography plugin's `prose`
           classes, so this doesn't depend on that plugin being installed.
           Targets exactly the two elements the system prompt guarantees
           the model will produce: one <h2> per subsection heading, one
           <p> per subsection body. */}
        <div
          className="px-6 py-6 sm:px-8 [&>h2]:mt-6 [&>h2]:mb-2 [&>h2]:text-lg [&>h2]:font-semibold [&>h2]:text-neutral-900 [&>h2:first-child]:mt-0 [&>p]:mb-4 [&>p]:leading-relaxed [&>p]:text-neutral-700 [&>p:last-child]:mb-0"
          dangerouslySetInnerHTML={{ __html: article.body }}
        />
      </article>
    </main>
  );
}
